---
title: 'Module 1: Introduction to R'
author: "Jeroen Claes | <jeroen.claes@kuleuven.be> | <jeroen@cropland.be>"
---

## 1. Installing and loading packages
```{r, include=FALSE}
tutorial::go_interactive()
```

```{r ex="library", type="sample-code"}
# We can't install packages here, but we can load some!

# Load the dplyr package


# Load the stringi package


# Load the ggplot2 package

```

```{r ex="library", type="solution"}
# We can't install packages here, but we can load some!

# Load the dplyr package
library(dplyr)

# Load the stringi package
library(stringi)

# Load the ggplot2 package
library(ggplot2)
```

```{r ex="library", type="sct"}
ex() %>% check_library("dplyr", not_called_msg="Don't forget to load the dplyr package", incorrect_msg="Remember that we use e.g., `library(dplyr)` to load packages")
ex() %>% check_library("ggplot2", not_called_msg="Don't forget to load the ggplot2 package", incorrect_msg="Remember that we use e.g., `library(dplyr)` to load packages")
ex() %>% check_library("stringi", not_called_msg="Don't forget to load the stringi package", incorrect_msg="Remember that we use e.g., `library(dplyr)` to load packages")
success_msg("Great!")
```


## 2. Objects, vectors, and basic mathematics
### 2.1 Objects and vectors

```{r ex="create_a", type="sample-code"}
# Create a variable a, equal to 5

# Create a variable b, equal to "myname"

# Create numeric vecotr c, equal to 1, 2, 3, 4

# Create a character vector d, in which you store the words "my", "teacher's", "name", "is", "jeroen"

# Print out a (type in "a", followed by)

# Print out b

# Print out c

# Print out d

```

```{r ex="create_a", type="solution"}
# Create a variable a, equal to 5
a <- 5
# Create a variable b, equal to "myname"
b <- "myname"
# Create numeric vector c, equal to 1, 2, 3, 4
c <-c(1, 2, 3, 4)
# Create a character vector d, in which you store the words "my", "teacher's", "name", "is", "jeroen"
d <- c("my", "teacher's", "name", "is", "jeroen")
# Print out a
a

# Print out b
b

# Print out c
c

# Print out d
d

```

```{r ex="create_a", type="sct"}
ex() %>% check_object("a") %>% check_equal()

ex() %>% check_object("d") %>% check_equal()
success_msg("Great!")
```

### 2.2 Using R as a calculator 
#### 2.2.1 Setting up your variables 
```{r ex="create_b", type="sample-code"}
# Create a variable a, equal to 15

# Create a variable b, equal to 10

# Create numeric vector c, equal to 1, 2, 3, 4

# Create a numeric vector d, equal to 5, 6, 7, 8
```

```{r ex="create_b", type="solution"}
# Create a variable a, equal to 5
a <- 15
# Create a variable b, equal to "myname"
b <- 10
# Create numeric vector c, equal to 1, 2, 3, 4
c <-c(1, 2, 3, 4)
# Create a numeric vector d, equal to 5, 6, 7, 8
d <- c(5, 6, 7, 8)
```

```{r ex="create_b", type="sct"}
ex() %>% check_object("a") %>% check_equal()
#test_output_contains("d", incorrect_msg = "Make sure to print everything!.")
success_msg("Great!")
```

#### 2.2.2 Summation 
```{r ex="add", type="pre-exercise-code"}
# Create a variable a, equal to 15
a<-15
# Create a variable b, equal to 10
b<-10
# Create numeric vector c, equal to 1, 2, 3, 4
c<- c(1, 2, 3, 4)
# Create a numeric vector d, equal to 5, 6, 7, 8
d<-c(5, 6, 7, 8)
```

```{r ex="add", type="sample-code"}
# Add a up to b

# Add b up to c

# Add c up to d
```

```{r ex="add", type="solution"}
# Add a up to b
a + b
# Add b up to c
b + c 
# Add c up to d
c + d
```

#### 2.2.3 Substraction 
```{r ex="substraction", type="pre-exercise-code"}
# Create a variable a, equal to 15
a<-15
# Create a variable b, equal to 10
b<-10
# Create numeric vector c, equal to 1, 2, 3, 4
c<- c(1, 2, 3, 4)
# Create a numeric vector d, equal to 5, 6, 7, 8
d<-c(5, 6, 7, 8)
```

```{r ex="substraction", type="sample-code"}
# Subtract b from a

# Subtract b from c

# Subtract c from d
```

```{r ex="substraction", type="solution"}
# Subtract b from a
a -b
# Subtract b from c
c -b 
# Subtract c from d
d - c
```

#### 2.2.4 Multiplication 
```{r ex="multiplication", type="pre-exercise-code"}
# Create a variable a, equal to 15
a<-15
# Create a variable b, equal to 10
b<-10
# Create numeric vector c, equal to 1, 2, 3, 4
c<- c(1, 2, 3, 4)
# Create a numeric vector d, equal to 5, 6, 7, 8
d<-c(5, 6, 7, 8)
```

```{r ex="multiplication", type="sample-code"}
# Multiply a by b

# Mutiply b by c

# Multiply c by d
```

```{r ex="multiplication", type="solution"}
# Multiply a by b
a * b
# Mutiply b by c
b * c
# Multiply c by d
c * d 
```

#### 2.2.5 Division 
```{r ex="division", type="pre-exercise-code"}
# Create a variable a, equal to 15
a<-15
# Create a variable b, equal to 10
b<-10
# Create numeric vector c, equal to 1, 2, 3, 4
c<- c(1, 2, 3, 4)
# Create a numeric vector d, equal to 5, 6, 7, 8
d<-c(5, 6, 7, 8)
```

```{r ex="division", type="sample-code"}
# Divide a by b

# Divide c by b

# Divide c by d
```

```{r ex="division", type="solution"}
# Divide a by b
a / b
# Divide c by b
c / b
# Divide c by d
c / b
```

### 3. Loading data from CSV

```{r ex="loadData", type="sample-code"}
# Load the readr package

# Load the course data from the course website to the object 'dataSet':
# http://www.jeroenclaes.be/statistics_for_linguistics/datasets/class2_balota_et_al_2007.csv

# Load dplyr

# The function 'glimpse' from the dplyr package will print the first copule of rows of the resulting data table as a list
glimpse(dataSet)


```

```{r ex="loadData", type="solution"}
# Load the readr package
library(readr)
# Load the course data from the course website to the object 'dataSet':
# http://www.jeroenclaes.be/statistics_for_linguistics/datasets/class2_balota_et_al_2007.csv
dataSet <- read_csv("http://www.jeroenclaes.be/statistics_for_linguistics/datasets/class2_balota_et_al_2007.csv")

# Load dplyr
library(dplyr)

# The function 'glimpse' from the dplyr package will print the first copule of rows of the resulting data table as a list
glimpse(dataSet)
```

```{r ex="loadData", type="sct"}

ex() %>% check_object("dataSet") %>% check_equal()
ex() %>% check_library("dplyr")
ex() %>% check_library("readr")
success_msg("Great!")
```